---
title: "Disciplinas"
author: "Joyce de Souza Sforzin"
date: "25/09/2019"
output:
  html_document:
   toc: yes
   code_folding: hide
   theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Conhecendo o curso de licenciatura em matemática.

<div style="text-align: justify;">

Todos quando estamos tentando descobrir qual curso fazer, passamos por alguns problemas da falta de informação e ficamos na dúvida "o que estudarei neste curso?", bom, meu intuito nessa página é lhe informar as disciplinas que vemos nesse curso e tentarei explicar o seu conteúdo ao menos das quais já cursei durante meus 2 anos de graduação, pois ainda sou apenas uma universitária descobrindo o que virá daqui para frente.
</div>

### Disciplinas do primeiro período 

<div style="text-align: justify;">
Ao entrarmos na universidade ficamos assustados em como será nossa resposta às dificuldades das matérias que veremos ao decorrer do curso. Sempre ouvimos que tudo é bem difícil, porém na Universidade Federal de Viçosa - *Campus* Florestal temos uma passagem gradativa entre as matérias subindo de nível nas dificuldades de acordo com que vamos indo para o próximo período.
  
  Essas matérias são :

* [**_MAF201_** - **Matemática Elementar**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=1&disciplina=MAF%20201#disciplina) : Conjuntos Numéricos. Funções elementares. Trigonometria e funções trigonométricas. Função exponencial e logarítmica. Introdução aos números complexos. Polinômios.

* [**_MAF135_** - **Geometria Analítica e Álgebra Linear**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=1&disciplina=MAF%20135#disciplina)(GAAL): Matrizes, sistemas de equações lineares e determinantes. Vetores no plano e no espaço. Cônicas e quádricas. Espaços vetoriais Euclidianos. Diagonalização de matrizes. Transformações lineares.

* [**_MAF109_** - **Resolução de Problemas**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=1&disciplina=MAF%20109#disciplina): Números naturais. Raízes de funções polinomiais. Números complexos de um ponto de vista geométrico. Funções trigonométricas. Triângulos: congruência; semelhança; relações métricas e trigonométricas. Áreas de figuras planas.
 
* [**_LEF100_** - **Português Instrumental**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=1&disciplina=LEF%20100#disciplina): Concepções de leitura e produção, considerando o enfoque tradicional e interacionista. Os sujeitos da leitura e da produção. Compreensão e expressão oral. Leitura e produção de textos informativos e acadêmicos.

* [**_CCF100_** - **Introdução a programação**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=1&disciplina=CCF%20100#disciplina): Fundamentos de Lógica de Programação. Algoritmo. Constantes e Variáveis. Estruturas de Controle. Estrutura de Repetição. Vetores. Matrizes.
</div>

### Disciplinas do segundo período
<div style="text-align: justify;">

Neste período continuamos com uma introdução ao nível universitário, mas aqui já conseguimos sentir um pouco mais de dificuldade. São matérias que começamos a entender e provar contas que fazíamos, mas não sabíamos de onde tinha vindo ou porque era verdade pra uns será a primeira vez estudando calculo apesar de ser uma matéria obrigatória no médio.

* [**_MAF100_** - **Colóquios de Matemática**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=2&disciplina=MAF%20100#disciplina): Seminários semanais proferidos por professores do Campus de Florestal e /ou convidados que abordarão temas sobre a estrutura do curso de Matemática da UFV (Licenciatura e Bacharelado), áreas de atuação, mercado de trabalho do profissional de Matemática.

* [**_MAF102_** - **Prática de Ensino de Matemática**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=2&disciplina=MAF%20102#disciplina): Estudo sobre os objetivos do ensino de Matemática e sobre a estrutura de uma aula de Matemática. Análise crítica de recursos didáticos, de livros didáticos antigos e atuais e de revistas especializadas.

* [**_MAF131_** - **Introdução à Álgebra**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=2&disciplina=MAF%20131#disciplina): Noções de lógica matemática. Conjuntos. Operações entre conjuntos. Relações. Funções ou aplicações. Operações binárias.

* [**_MAF141_** - **Cálculo Diferencial e Integral I**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=2&disciplina=MAF%20141#disciplina): Funções. Limites e continuidade. Derivadas. Aplicações da derivada. Integrais. Aplicações da integral. Integrais impróprias e aplicações.

* [**_MAF151_** - **Fundamentos de Geometria e Desenho Geométrico**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=2&disciplina=MAF%20151#disciplina): Axiomas da Geometria Plana. Teorema do ângulo externo e conseqüências. O postulado das paralelas e a Geometria Euclidiana. Semelhança de triângulos. Círcunferências. Áreas e comprimentos. Construções Geométricas com régua e compasso.
</div>

### Disciplinas do terceiro período  
<div style="text-align: justify;">

Antes de falar sobre as matérias, é importante ter em vista que a partir do terceiro período alguns criterios são necessarios de requisitos para faze-las. Dois são os tipos de requisitos:

**Pré-requisito**: será um critério que o aluno já deverá ter cumprido.

**Co-requisito**: será um critério que o aluno poderá fazer em paralelo.

*Exemplificando*:

**Primeiro caso**: Um aluno vai tentar se matricular na disciplina de CÁLCULO II, entretanto existe uma disciplina CÁLCULO I, que é importante para que ele consiga assimilar o conteúdo. Nesse caso, CÁLCULO I é pré-requisito para que ele consiga se matricular em CÁLCULO II, portanto ele deverá ter sido aprovado já nesta primeira.

**Segundo caso**: Um aluno vai cursar TÉCNICAS DE PROGRAMAÇÃO, mas para isso ele tem que cursar também LABORATÓRIO DE PROGRAMAÇÃO. Este é um caso de co-requisito. Ou seja, o aluno poderá cursar as duas disciplinas ao mesmo tempo.

* [**_EDF133_** - **Educação e Realidade Brasileira**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=3&disciplina=EDF%20133#disciplina): Introdução aos estudos educacionais. O fenômeno educativo na sociedade contemporânea. Tópicos atuais da educação formal e não-formal.

* [**_MAF103_** - **Prática de Ensino de Matemática II**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=3&disciplina=MAF%20103#disciplina): Estudo sobre os objetivos do ensino de Matemática no Ensino Fundamental. O Ensino da Álgebra. Propostas curriculares atuais e recursos didáticos para a abordagem da álgebra e das funções na escola básica. O Ensino da geometria.

* [**_MAF105_** - **Iniciação à Estatística**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=3&disciplina=MAF%20105#disciplina): Conceitos introdutórios. Estatística descritiva. Regressão linear simples e correlação amostral. Introdução à teoria da probabilidade. Variáveis aleatórias discretas e contínuas. Funções de variáveis aleatórias. Esperança matemática, variância e covariância.
 
* [**_MAF143_** - **Calculo Diferencial e Integral II**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=3&disciplina=MAF%20143#disciplina): Sequências e séries infinitas. Séries de potências. Equações paramétricas, coordenadas polares e cônicas. Funções de várias variáveis.

* [**_MAF232_** - **Fundamentos da Aritmética**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=3&disciplina=MAF%20232#disciplina): Sistemas de numeração. Indução, boa ordenação e divisão euclidiana. O teorema fundamental da aritmética. Equações diofantinas lineares e congruências. Os números racionais. Tópicos sobre números inteiros.

* [**_FIF201_** - **Física I**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=3&disciplina=FIF%20201#disciplina): Medidas em física. Movimento de translação. Dinâmica da partícula. Trabalho e energia. Sistemas de partículas. Dinâmica da rotação.

* [**_FIF121_** - **Laboratório de Física Geral**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=3&disciplina=FIF%20121#disciplina): Medidas, erros e gráficos. Cinemática e dinâmica da partícula e de corpos rígidos. Oscilações, ondas e óptica. Termodinâmica. Eletricidade e magnetismo.
</div>

### Disciplinas do quarto período

<div style="text-align: justify;">

Neste período do qual estou cursando, começamos a ver o que é a real dificuldade de grande parte das matérias o que é o termo "nível universitário" não que as matérias anteriores tenham sido fáceis pois não foram, mas agora percebemos que as outras matérias forma do modo que foram pra chegarmos agora em que tudo que aprendemos no primeiro e segundo período será revisto e unido a outras aplicações.

* [**_FIF202_** - **Física II**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=4&disciplina=FIF%20202#disciplina): Gravitação. Oscilações. Fluidos. Ondas Mecânicas. Temperatura e calor. Propriedades térmicas da matéria. Primeira Lei da Termodinâmica. Segunda Lei da Termodinâmica

* [**_MAF172_** - **Matemática Computacional**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=4&disciplina=MAF%20172#disciplina): Uso de editores de textos e planilhas eletrônicas para confecção de textos matemáticos. Recursos de informática para auxiliar no ensino de geometria e de aritmética nos Ensinos Fundamental e Médio. Pesquisa científica na rede de computadores.

* [**_MAF243_** - **Cálculo Diferencial e Integral III**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=4&disciplina=MAF%20243#disciplina): Integrais duplas e triplas. Funções vetoriais. Cálculo vetorial.

* [**_MAF331_** - **Álgebra I**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=4&disciplina=MAF%20331#disciplina): Introdução à teoria de Grupos. Introdução à teoria de anéis e corpos. Anéis de polinômios. Grupos solúveis.

* [**_EDF117_** - **Psicologia do Desenvolvimento e da Aprendizagem**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=4&disciplina=EDF%20117#disciplina): A relação da psicologia com a educação. Introdução ao estudo dos processos de desenvolvimento e de aprendizagem. Enfoque comportamentalista e seus desdobramentos na prática educacional. Enfoque psicanalítico e seus desdobramentos na prática educacional.
</div>

### Disciplinas do quinto período

<div style="text-align: justify;">

Daqui em diante não posso comentar sobre por não ter uma opnião já formada, pretendo com o tempo ir editando cada diciplina, para um melhor suporte para todos.

* [**_MAF250_** - **Geometria Espacial**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=5&disciplina=MAF%20250#disciplina): Conceitos primitivos e postulados. Retas e planos: paralelismo e perpendicularismo. Diedros. Triedros. Poliedros convexos. Sólidos: prismas, pirâmides, cilindros, cones e troncos. Esfera. Inscrição e circunscrição de sólidos.

* [**_EDF144_** - **Estrutura e Funcionamento do Ensino Fundamental e Médio**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=5&disciplina=EDF%20144#disciplina): Fundamentos filosóficos, históricos e sócio-políticos. O sistema escolar brasileiro. Fundamentos legais. O ensino fundamental e médio na Lei 9.394/96 e legislação complementar.
 
* [**_FIF203_** - **Física III**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=5&disciplina=FIF%20203#disciplina): Força e campos elétricos. Potencial elétrico. Capacitância e dielétricos. Resistência, correntes e circuitos elétricos. Campo magnético. Lei de Ampère e Lei de Biot-Sarvat. Lei de Indução de Faraday. Indutância. Correntes alternadas.

* [**_MAF203_** - **Matemática Finita**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=5&disciplina=MAF%20203#disciplina): Análise combinatória. Binômio de Newton. Introdução à probabilidade. Progressão e matemática financeira.

* [**_MAF305_** - **Hitória da Matemática**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=5&disciplina=MAF%20305#disciplina): Tópicos de história da matemática.

* [**_MAF341_** - **Análise I**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=5&disciplina=MAF%20341#disciplina): Números reais. Sequências e séries. Topologia na reta. Limite de funções definidas em intervalos. Funções contínuas. Derivadas de funções. Aplicações da Derivada. A integral de Riemann.
</div>

### Disciplinas do sexto período
<div style="text-align: justify;">

* [**_MAF394_** - **Estágio Supervisionado de Matemática na Educação Básica A**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=6&disciplina=MAF%20394#disciplina): Observação e participação nas Escolas de Ensino Fundamental nas aulas de matemática. Atividades de estágio de observação e apoio ao professor. Aulas simuladas. Elaboração e implementação. Técnicas de ensino. Aula expositiva. Trabalho em grupo.

* [**_EDF155_** - **Didática**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=6&disciplina=EDF%20155#disciplina): A didática na formação do professor. Diferentes concepções de ensino no Brasil. Noções de currículo. A sala de aula como espaço interdisciplinar. A construção do conhecimento em sala de aula. Planejamento de ensino e Avaliação.

* [**_MAF335_** - **Álgebra Linear A**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=6&disciplina=MAF%20335#disciplina): Espaços vetoriais. Álgebra das transformações lineares. Grupo de transformações lineares invertíveis. Transformações lineares e matrizes. Diagonalização de operadores.

* [**_MAF207_** - **Prática de Ensino de Matemática III**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=6&disciplina=MAF%20207#disciplina): Análise dos PCNs e dos temas transversais. Planejamento didático no Ensino Fundamental e Médio. Projeto Político Pedagógico da Escola de Ensino Básico.

* [**_MAF340_** - **Equações Diferenciais Ordinárias I**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=6&disciplina=MAF%20340#disciplina) (EDO): Introdução ao estudo das equações diferenciais ordinárias. Equações de primeira ordem. Equações de segunda ordem não lineares. Equações lineares de segunda ordem. Resolução em séries de potências. Sistemas de equações diferenciais lineares.
</div>

### Disciplinas do sétimo período
<div style="text-align: justify;">

* [**_MAF271_** - **Cálculo Numérico**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=7&disciplina=MAF%20271#disciplina): Introdução. Solução de equações não-lineares. Interpolação e aproximações. Integração. Sistemas de equações lineares. Resolução de equações diferenciais ordinárias.

* [**_MAF208_** - **Prática de Ensino de Matemática IV**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=7&disciplina=MAF%20208#disciplina): Análise e discussão das diversas propostas curriculares de matemática para o Ensino Fundamental e Médio. Avaliação da aprendizagem. Principais sistemas de avaliação das redes de ensino. Análise e discussão de textos.

* [**_MAF490_** - **Oficinas de Matemática**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=7&disciplina=MAF%20490#disciplina): Elaboração e execução de eventos e oficinas matemáticas. Organização de eventos, oficinas e jornadas. Produção de seminários, palestras e minicursos. 

* [**_MAF395_** - **Estágio Supervisionado de Matemática na Educação Básica B**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=7&disciplina=MAF%20395#disciplina): Observação e participação nas Escolas de Ensino Médio nas aulas de matemática. Atividades de estágio de observação e apoio ao professor. Aulas simuladas: elaboração e implementação. Técnicas de ensino. 

* [**_MAF491_** - **Monografia e Seminário I**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=7&disciplina=MAF%20491#disciplina): Elaboração de um projeto de monografia sobre tópico de Matemática, Educação Matemática ou áreas afins, escolhido para estudo sob a orientação do professor da disciplina. Sugestão do roteiro a ser seguido para a execução dessa disciplina. 
</div>

### Disciplinas do oitavo período 
<div style="text-align: justify;">

* [**_MAF492_** - **Monografia e Seminário II**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=8&disciplina=MAF%20492#disciplina): Elaboração de uma monografia sobre o tópico de Matemática, Educação Matemática ou áreas afins, escolhido para estudo sob orientação do professor da disciplina, e sua defesa em seminário do departamento. 

* [**_MAF295_** - **Atividades Complementares**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=8&disciplina=MAF%20295#disciplina): Nessa disciplina será contabilizada uma carga horária de no mínimo 210 horas na participação do aluno em: projetos educacionais, cursos de verão, cursos de extensão, participação em palestras, congressos, seminários e similares, atividades de extensão.

* [**_MAF396_** - **Estágio Supervisionado de Matemática na Educação Básica C**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=8&disciplina=MAF%20396#disciplina): Observação e participação nas Escolas de Ensino Básico nas aulas de matemática. Atividades de estágio de observação e apoio ao professor. Aulas simuladas: elaboração. Elaboração, implementação e avaliação de planos de aula: regência de aula. 


* [**_LEF280_** - **LIBRAS Língua Brasileira de Sinais**](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=8&disciplina=LEF%20280#disciplina): O sujeito surdo. Noções linguísticas de libras. A gramática da língua. Aspectos sobre a educação dos surdos. Teoria da tradução e interpretação. Introdução às técnicas de tradução em Libras/Português. Introdução às técnicas de tradução em Português/Libras.
</div>

### Optativas
<div style="text-align: justify;">

Além de todas nossas matérias, optativas também são disponibilizadas para os alunos que queiram aprofundar em alguma matéria, ou até mesmo ver sobre algo que não está presente em nosso curso. Segue abaixo essas optativas e caso queira saber mais sobre elas recomendo que você entre no site:

[Disciplinas optativas](http://www.catalogo.ufv.br/interno.php?ano=2019&curso=LCM&campus=caf&complemento=*&periodo=0)
</div>

**Código**|**Nome**                                    |**Código**|**Nome**
------|----------------------------------------|------|----------------------------------------------------
ADF281|Matemática Financeira			             |MAF332|Álgebra para Licenciatura	
BQF101|Laboratório de Bioquímica               |MAF334|Álgebra II
BQF103|Bioquímica I	                           |MAF336|Álgebra Linear I	
CBF111|Biologia Celular	                       |MAF337|Álgebra Linear B
CBF115|Biologia de Microrganismos              |MAF342|Análise para Licenciatura	
CBF131|Ecologia Básica	                       |MAF343|Variáveis Complexas
CBF170|Biologia e Ecologia de Algas e Briófitas|MAF344|Tópicos de Equações Diferenciais Ordinárias
CBF220|Anatomia Humana	                       |MAF345|Análise II	
CBF221|Histologia Básica                       |MAF346|Análise III
CBF240|Genética	                               |MAF347|Análise Real I	
CBF260|Zoologia dos Invertebrados I            |MAF348|Análise Real II	
EDF110|Psicologia			                         |MAF350|Introdução às Geometrias Não-Euclidianas	
EDF127|Filosofia da Ciência                    |MAF392|Tópicos Especiais IV		
EDF227|Concepção Filosófica da Educação        |MAF393|Tópicos Especiais III		
EDF230|Sociologia da Educação			             |MAF431|Curvas Algébricas	
EDF314|Dinâmica de Grupo		                   |MAF432|Introdução à Teoria dos Números			
LEF101|Português Instrumental II		           |MAF433|Teoria dos Números
LEF215|Inglês I	                               |MAF448|Espaços Métricos
LEF216|Inglês II	                             |MAF451|Geometria Diferencial
LEF225|Francês Instrumental I		               |MAF452|Topologia Geral		
LEF226|Francês Instrumental II	               |MAF472|Biomatemática	
MAF137|Introdução à Álgebra Linear		         |MAF493|Tópicos Especiais I		
MAF152|Geometria Analítica			               |MAF494|Tópicos Especiais II		
MAF220|Métodos de Contagem			               |QMF100|Química Geral	
MAF221|Teorema de Pitágoras e Áreas			       |QMF101|Formação Profissional e Áreas de Atuação do Químico		
MAF246|Construção dos Números Reais	           |QMF107|Laboratório de Química Geral	
MAF251|Geometria Descritiva                    |QMF145|História da Química
MAF252|Introdução à Teoria dos Grafos          |TBC493|Tópicos Especiais em Políticas de Saúde e Cidadania
MAF261|Estatística Experimental                | 