---
title: "Projetos de Pesquisa"
author: "Marcia Moraes Rodrigues"
date: "19/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

PROGRAMAS DE INICIAÇÃO CIENTÍFICA EXISTENTES UFV FLORESTAL.

Para participar dos Programas de Iniciação Científica da Universidade Federal de Viçosa – Campus Florestal, o interessado deverá primeiro escolher o programa que mais se encaixa no seu perfil. Para isso, deve estar atento às datas de inscrição presentes em cada edital. Em seguida, procurar o Professor com formação na sua área de interesse e apresentar claramente seus objetivos. 
Se o objetivo for trabalhar com Sistemas Dinâmicos, o candidato poderá procurar um dos Professores:

•	Alexandre Alvarenga Rocha, graduado em Matemática pela Universidade Federal de Viçosa em 2006, mestrado em Matemática pela Universidade Federal de Minas Gerais em 2009 e doutorado em Matemática pela Universidade Federal de Minas Gerais em 2013. 

•	Justino Muniz Júnior, graduado em Matemática pela Universidade Federal de Ouro Preto em 2006 e mestrado em Matemática pela Universidade Federal de Minas Gerais com ênfase em Sistemas Dinâmicos em 2009. 

•	Lucas Carvalho Silva, licenciado e mestrado em Matemática pela Universidade Federal de Viçosa.

•	Lúcio Paccori Lima, graduado em Matemática pela Universidad Nacional de San Agustín de Arequipa em 1993 e mestrado em Matemática pela Universidade Federal de Minas Gerais em 1998. 

•	Luiz Gustavo Perona Araújo, graduado em Matemática pela Universidade Federal de Minas Gerais em 2009, mestrado em 2012 e doutorado em 2017 em Matemática pela Universidade Federal de Minas Gerais. 

•	Sérgio Henrique Nogueira, graduado em Matemática pela Universidade Federal de Viçosa em 1997 e mestrado em Matemática pela Universidade de São Paulo em 2002. 

Se a área de interesse for pela Estatística o aluno poderá procurar um dos Professores:

•	Fernando de Souza Bastos, licenciado em Matemática pela Universidade Federal de Viçosa em 2007, mestrado em Estatística Aplicada e Biometria pela Universidade Federal de Viçosa em 2010 e doutorado em Estatística pela Universidade Federal de Minas Gerais em 2018. 

•	Guaraci de Lima Requena, bacharelado em Matemática Aplicada pelo Instituto de Biociências, Letras e Ciências Exatas da Universidade Estadual Paulista em 2011, mestrado em Estatística pela Universidade Federal de São Carlos em 2014, doutorado em Estatística pelo Instituto de Matemática e Estatística da Universidade de São Paulo em 2018.

Se o desejo do candidato for atuar na área de Biomatemática, poderá procurar pelo Professor:

•	Mehran Sabeti, bacharelado e licenciatura em matemática pela Universidade Federal do Espírito Santo em 2004, mestrado em Matemática Aplicada pela Universidade Federal do Paraná em 2007 e doutorado em Matemática pela Universidade Federal de Pernambuco em 2011. 

Quando o interesse estiver direcionado para a área da Educação Matemática, deverá procurar pelos Professores:

•	Lúcia Helena dos Santos Lobato, graduado em Matemática pela Faculdade de Filosofia Ciências e Letras de Belo Horizonte em 1992, especialização em Educação Matemática também pela Faculdade de Filosofia Ciências e Letras de Belo Horizonte em 1993 e mestrado em Mídia e Conhecimento, pela Universidade Federal de Santa Catarina em 2003, doutorado em Educação Matemática pela Universidade Bandeirante de São Paulo em 2018.  

•	Gerson Geraldo Chaves, graduado em Matemática pelas Faculdades Integradas Newton Paiva em 1994, pós-graduado em Educação pela Faculdade de Educação São Luís em 1998, mestrado em Ciências pela Universidade Federal Rural do Rio de Janeiro em 2011 e doutorado em Educação Matemática pela Universidade Anhanguera de São Paulo em 2018.

Se prioridade de interesse estiver relacionada à Álgebra, deverá procurar os Professores: 

•	Danielle Franco Nicolau, graduada em Matemática pelo Centro Universitário de Belo Horizonte em 2005, mestrado em Matemática pela Universidade Federal de Minas Gerais em 2010 e doutorado em Matemática pela Universidade Federal de Minas Gerais em 2014. 

•	Luís Felipe Gonçalves Fonseca, graduado em Matemática pela Universidade Federal de Minas Gerais em 2007, mestrado em Matemática pela Universidade Federal de Minas Gerais em 2010 e doutorado em Matemática pela Universidade de Brasília em 2013. 


Caso a proposta seja aceita, o orientador irá submeter o projeto para avaliação conforme consta no edital. Bons estudos!

PIBIC/CNPQ

O Programa Institucional de Bolsas de Iniciação Científica (PIBIC), do Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPQ), tem por objetivo despertar a vocação científica e incentivar novos talentos entre estudantes de graduação. O PIBIC visa ainda: contribuir para a formação de recursos humanos para a pesquisa; para a formação científica de recursos humanos que se dedicarão a qualquer atividade profissional; estimular uma maior articulação entre a graduação e a pós-graduação; qualificar alunos para os programas de pós-graduação e reduzir o tempo médio de sua permanência na pós-graduação; estimular pesquisadores produtivos a envolverem estudantes de graduação nas atividades científica, tecnológica, profissional e artístico-cultural; e proporcionar ao bolsista, orientado por pesquisador qualificado, a aprendizagem de técnicas e métodos de pesquisa, bem como estimular o desenvolvimento do pensar cientificamente e da criatividade, decorrentes das condições criadas pelo confronto direto com os problemas de pesquisa. 
Período de inscrições: abril a maio. 
Maiores informações no Edital: <ahref="http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf" class="uri">http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf</a>

PIBIC/CNPQ AF 

O Programa Institucional de Bolsas de Iniciação Científica - Ações Afirmativas (PIBIC), do Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPQ), é um programa que visa ampliar a oportunidade de formação técnico-científica pela concessão de bolsas de Iniciação Científica para os alunos do Ensino Superior, cuja inserção no ambiente acadêmico se deu por uma ação afirmativa. Tem como objetivos: contribuir para a formação científica de recursos humanos entre os beneficiários de políticas de ações afirmativas de qualquer atividade profissional; ampliar o acesso e a integração dos estudantes beneficiários de políticas de ações afirmativas à cultura científica; e fortalecer a política de ação afirmativa existente nas instituições. 
Público alvo: Alunos que entraram com alguma ação afirmativa de acordo com a Lei nº 12.711, de 2012. 
Período de inscrições: abril a maio. 
Maiores informações no Edital: <a href="http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf" class="uri">http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf</a>

PIBIC EM/CNPQ/UFV

O objetivo do Programa Institucional de Bolsas de Iniciação Científica – Ensino Médio (PIBIC-EM), é fortalecer o processo de disseminação das informações e conhecimentos científicos e tecnológicos básicos, bem como desenvolver as atitudes, habilidades e valores necessários à educação científica e tecnológica dos estudantes do Ensino Médio, ampliando sua formação e permitindo que mantenham contato com um projeto científico, despertando o interesse pela pesquisa científica. Os projetos submetidos, pelos orientadores, deverão ter um caráter de formação e nível de execução compatível com alunos do Ensino Médio. 
Público alvo: Alunos do Ensino Médio.
Período de inscrições: abril a maio.
Maiores informações no Edital: <a href="http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf" class="uri">http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf</a>

PIBIC/FAPEMIG (TEMPORARIAMENTE SUSPENSO)

O Programa Institucional de Bolsas de Iniciação Científica (PIBIC), em parceria com a Fundação de Amparo à Pesquisa do Estado de Minas Gerais (FAPEMIG), tem a finalidade de despertar e desenvolver o interesse de estudantes de graduação pelas atividades de pesquisa nas diversas áreas do conhecimento e especialidades. Como parte da política da Diretoria de Pesquisa e Pós-Graduação/Pró-Reitoria de Pesquisa e Pós-Graduação objetiva-se, por meio deste programa, ampliar as oportunidades dos docentes que concluíram o doutorado recentemente e demais doutorados de orientarem bolsistas de iniciação científica e promover o fortalecimento da linha de pesquisa em que atuam.

BIC-JUNIOR/FAPEMIG (TEMPORARIAMENTE SUSPENSO)

O Programa BIC-JUNIOR/FAPEMIG tem por finalidade, despertar em estudantes do Ensino Fundamental, Médio e de Educação Profissional da Rede Pública, a vocação científica para a pesquisa, concedendo bolsas para participarem de projetos/atividades de pesquisa ou de extensão científica, tecnológica ou de inovação, orientados por pesquisador qualificado. 
Período de atividades: março (ano corrente) a fevereiro (ano seguinte)

FUNARBIC

O programa propõe ampliar as oportunidades de orientação de iniciação científica aos docentes que concluíram o doutorado nos últimos cinco anos, promovendo fortalecimento da linha de pesquisa em que atuam. 
Período de inscrições: abril a maio 
Maiores informações no Edital: <a href="http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf" class="uri">http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf</a>

PIBITI/CNPQ

O Programa Institucional de Bolsas de Iniciação em Desenvolvimento Tecnológico e Inovação (PIBITI), é um programa que estimula a participação de estudantes do Ensino Superior às atividades relacionadas ao desenvolvimento tecnológico e processos de inovação. Os projetos no âmbito do PIBITI deverão contribuir para formação de recursos humanos que se dedicarão ao fortalecimento da capacidade inovadora das empresas no Brasil. Além disso, o PIBITI deverá contribuir para a formação do cidadão pleno com condições de participar de forma criativa na sua comunidade. Assim, as propostas participantes desse Edital deverão mostrar comprovada interação com empresas e/ou comunidades, explicitando a participação do estudante dentro do projeto.
Período de inscrições: abril a maio.
Maiores informações no Edital: <a href="http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf" class="uri">http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf</a>

PIVIC

O Projeto de Pesquisa de Iniciação Científica Voluntária (PIVIC), é um programa que tem por objetivo dar oportunidade aos alunos de graduação, que não possuem bolsa de órgãos financiadores, de se iniciarem nas atividades de pesquisa junto a pesquisadores da UFV em seus trabalhos e projetos de pesquisa. Este vínculo não implicará em recebimento de bolsa ou qualquer fonte financeira. A UFVCREDI, SICOOB UFVCredi e a Pró-Reitoria de Pesquisa e Pós-Graduação, da Universidade Federal de Viçosa, comunicam que estarão abertas inscrições de abril a maio para a concessão de bolsas de iniciação científica a cooperados, filhos ou dependentes de cooperados da SICOOB UFVCredi. Os cooperados deverão ser associados da SICOOB UFVCredi há pelo menos seis meses e devem estar em dia com suas obrigações com a cooperativa.
Maiores informações no Edital: <a href="http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf" class="uri">http://www.ppg.ufv.br/wp-content/uploads/2013/07/Edital-PIBIC-UFV-2019-2020-GERAL-.pdf</a>
